
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('US_STATES').del()
    .then(function () {
      // Inserts seed entries
      return knex('US_STATES').insert([
        {id: 1, STATE_CODE: 'AL', STATE_NAME: 'Alabama'},
        {id: 2, STATE_CODE: 'AK', STATE_NAME: 'Alaska'},
        {id: 3, STATE_CODE: 'AZ', STATE_NAME: 'Arizona'},
        {id: 4, STATE_CODE: 'AR', STATE_NAME: 'Arkansas'},
        {id: 5, STATE_CODE: 'CA', STATE_NAME: 'California'},
        {id: 6, STATE_CODE: 'CO', STATE_NAME: 'Colorado'},
        {id: 7, STATE_CODE: 'CT', STATE_NAME: 'Connecticut'},
        {id: 8, STATE_CODE: 'DE', STATE_NAME: 'Delaware'},
        {id: 9, STATE_CODE: 'DC', STATE_NAME: 'District of Columbia'},
        {id: 10, STATE_CODE: 'FL', STATE_NAME: 'Florida'},
        {id: 11, STATE_CODE: 'GA', STATE_NAME: 'Georgia'},
        {id: 12, STATE_CODE: 'HI', STATE_NAME: 'Hawaii'},
        {id: 13, STATE_CODE: 'ID', STATE_NAME: 'Idaho'},
        {id: 14, STATE_CODE: 'IL', STATE_NAME: 'Illinois'},
        {id: 15, STATE_CODE: 'IN', STATE_NAME: 'Indiana'},
        {id: 16, STATE_CODE: 'IA', STATE_NAME: 'Iowa'},
        {id: 17, STATE_CODE: 'KS', STATE_NAME: 'Kansas'},
        {id: 18, STATE_CODE: 'KY', STATE_NAME: 'Kentucky'},
        {id: 19, STATE_CODE: 'LA', STATE_NAME: 'Louisiana'},
        {id: 20, STATE_CODE: 'ME', STATE_NAME: 'Maine'},
        {id: 21, STATE_CODE: 'MD', STATE_NAME: 'Maryland'},
        {id: 22, STATE_CODE: 'MA', STATE_NAME: 'Massachusetts'},
        {id: 23, STATE_CODE: 'MI', STATE_NAME: 'Michigan'},
        {id: 24, STATE_CODE: 'MN', STATE_NAME: 'Minnesota'},
        {id: 25, STATE_CODE: 'MS', STATE_NAME: 'Mississippi'},
        {id: 26, STATE_CODE: 'MO', STATE_NAME: 'Missouri'},
        {id: 27, STATE_CODE: 'MT', STATE_NAME: 'Montana'},
        {id: 28, STATE_CODE: 'NE', STATE_NAME: 'Nebraska'},
        {id: 29, STATE_CODE: 'NV', STATE_NAME: 'Nevada'},
        {id: 30, STATE_CODE: 'NH', STATE_NAME: 'New Hampshire'},
        {id: 31, STATE_CODE: 'NJ', STATE_NAME: 'New Jersey'},
        {id: 32, STATE_CODE: 'NM', STATE_NAME: 'New Mexico'},
        {id: 33, STATE_CODE: 'NY', STATE_NAME: 'New York'},
        {id: 34, STATE_CODE: 'NC', STATE_NAME: 'North Carolina'},
        {id: 35, STATE_CODE: 'ND', STATE_NAME: 'North Dakota'},
        {id: 36, STATE_CODE: 'OH', STATE_NAME: 'Ohio'},
        {id: 37, STATE_CODE: 'OK', STATE_NAME: 'Oklahoma'},
        {id: 38, STATE_CODE: 'OR', STATE_NAME: 'Oregon'},
        {id: 39, STATE_CODE: 'PA', STATE_NAME: 'Pennsylvania'},
        {id: 40, STATE_CODE: 'PR', STATE_NAME: 'Puerto Rico'},
        {id: 41, STATE_CODE: 'RI', STATE_NAME: 'Rhode Island'},
        {id: 42, STATE_CODE: 'SC', STATE_NAME: 'South Carolina'},
        {id: 43, STATE_CODE: 'SD', STATE_NAME: 'South Dakota'},
        {id: 44, STATE_CODE: 'TN', STATE_NAME: 'Tennessee'},
        {id: 45, STATE_CODE: 'TX', STATE_NAME: 'Texas'},
        {id: 46, STATE_CODE: 'UT', STATE_NAME: 'Utah'},
        {id: 47, STATE_CODE: 'VT', STATE_NAME: 'Vermont'},
        {id: 48, STATE_CODE: 'VA', STATE_NAME: 'Virginia'},
        {id: 49, STATE_CODE: 'WA', STATE_NAME: 'Washington'},
        {id: 50, STATE_CODE: 'WV', STATE_NAME: 'West Virginia'},
        {id: 51, STATE_CODE: 'WI', STATE_NAME: 'Wisconsin'},
        {id: 52, STATE_CODE: 'WY', STATE_NAME: 'Wyoming'},
      ]);
    });
};
